// Fiches métier — prestations intellectuelles (structure « services ») et modèles génériques. Références = pistes à confirmer.
export const PI = [
  {
    code: 'PRESTATIONS_INTELLECTUELLES', libelle: 'Études, conseil et assistance technique (prestations intellectuelles)', description: 'Études, expertises, conseil, assistance technique, élaboration de stratégies et de plans.', famille: 'SERVICES',
    contexte: 'Préciser la politique ou le programme visé, les travaux déjà réalisés et la décision que l\'étude doit éclairer.',
    contextePoints: ['Décision ou action que l\'étude doit permettre', 'Études et données existantes à exploiter'],
    objectifs: ['Réaliser [●] et formuler des recommandations opérationnelles chiffrées.', 'Fournir à l\'autorité les éléments pour décider avant le [●].', 'Transférer la méthode et les outils aux équipes de l\'institution.'],
    prestations: ['Revue documentaire et collecte de données : [●]', 'Analyse et diagnostic selon la méthodologie proposée : [●]', 'Consultations des parties prenantes : [●] entretiens / ateliers', 'Élaboration de scénarios et recommandations chiffrées : [●]', 'Atelier de restitution et de validation', 'Transfert de compétences aux équipes de l\'autorité', 'Rédaction du rapport final et des annexes'],
    livrables: ['Rapport de démarrage avec méthodologie et calendrier', 'Rapport provisoire de diagnostic', 'Rapport final intégrant les observations', 'Synthèse opérationnelle et présentation de restitution'],
    profil: ['Chef de mission (diplôme de niveau [●] et [●] ans d\'expérience)', 'Experts thématiques selon les besoins', 'Références d\'études comparables', 'Connaissance du contexte sénégalais', 'Moyens de collecte de données'],
    references: ['Termes de référence types de la DCMP pour les prestations intellectuelles (à confirmer)', 'Règles de confidentialité des données publiques', 'Propriété des livrables par l\'autorité'],
    vigilance: ['Ne pas noter les offres sur le prix avant la qualité technique (sélection selon le mode prévu)', 'Éviter les conflits d\'intérêts du consultant', 'Définir précisément les livrables et le nombre de jours-experts', 'Cession des droits sur les livrables'],
    reception: ['Rapports conformes au plan convenu', 'Observations de l\'autorité intégrées', 'Atelier de restitution tenu', 'Livrables remis dans les formats convenus'],
    dureePoints: ['Délais d\'examen des rapports par l\'autorité', 'Disponibilité des parties prenantes'],
    questions: ['Quelle décision ou quel programme l\'étude doit-elle éclairer ?', 'Quelles études et données existent déjà ?', 'Quels livrables et quel calendrier ?', 'Quel profil d\'équipe est nécessaire ?', 'Le transfert de compétences est-il attendu ?'],
    criteres: [['Compréhension des TDR et méthodologie', 35], ['Qualification et expérience de l\'équipe', 40], ['Références du cabinet', 15], ['Plan de travail et transfert de compétences', 10]],
    seuil: 75,
  },
  {
    code: 'ETUDES_MAITRISE_OEUVRE', libelle: 'Études techniques, maîtrise d\'œuvre et contrôle des travaux', description: 'Études de faisabilité et d\'exécution, maîtrise d\'œuvre, contrôle et surveillance de travaux, assistance à la réception.', famille: 'SERVICES',
    contexte: 'Préciser l\'ouvrage, le stade des études (APS, APD, DCE), la mission confiée et le calendrier des travaux.',
    contextePoints: ['Ouvrage concerné et programme', 'Stade d\'avancement et missions confiées (conception, DCE, suivi)'],
    objectifs: ['Établir les études [APS / APD / exécution] et le dossier de consultation des entreprises (DCE) de [●].', 'Assurer le contrôle technique, administratif et financier des travaux.', 'Garantir la conformité des ouvrages réalisés aux plans et au cahier des charges.'],
    prestations: ['Relevés, études de sol et diagnostics : [●]', 'Avant-projet sommaire et détaillé : [●]', 'Dossier de consultation des entreprises (plans, devis, CCTP) : [●]', 'Assistance à la passation des marchés de travaux', 'Direction et surveillance des travaux : [●] visites par semaine', 'Contrôle des décomptes, des essais et des matériaux', 'Assistance à la réception et établissement du dossier des ouvrages exécutés'],
    livrables: ['Rapports d\'études par phase (APS, APD)', 'DCE complet validé', 'Rapports mensuels de chantier', 'Procès-verbaux de réception et dossier des ouvrages exécutés'],
    profil: ['Chef de mission ingénieur ou architecte', 'Ingénieurs spécialisés (structures, VRD, électricité, etc.)', 'Résident de chantier à temps plein', 'Moyens de topographie et de laboratoire', 'Références de missions similaires'],
    references: ['Règles de calcul et de construction en vigueur', 'Réglementation de l\'urbanisme et de la construction (à confirmer)', 'Ordre des architectes et des ingénieurs : inscription des intervenants'],
    vigilance: ['Indépendance du contrôleur par rapport à l\'entreprise', 'Rémunération par pourcentage : éviter l\'incitation à augmenter le coût', 'Surveillance en continu et non seulement en visites', 'Contrôle des quantités réellement exécutées'],
    reception: ['Études complètes et approuvées', 'Rapports de chantier réguliers', 'Décomptes vérifiés', 'DOE remis avant solde de la mission'],
    dureePoints: ['Durée des études et des travaux contrôlés', 'Période de garantie'],
    questions: ['Quel ouvrage et à quel stade (études, DCE, contrôle) ?', 'Quelle mission exactement est confiée ?', 'Quelle durée des travaux à surveiller ?', 'Faut-il un résident permanent sur le chantier ?', 'Les études de sol et relevés existent-ils ?'],
    criteres: [['Méthodologie et organisation de la mission', 25], ['Qualification du chef de mission et de l\'équipe', 40], ['Références de missions similaires', 20], ['Moyens et logistique', 10], ['Plan de contrôle qualité', 5]],
    seuil: 75,
  },
  {
    code: 'ETUDES_ENVIRONNEMENTALES_SOCIALES', libelle: 'Études d\'impact environnemental et social', description: 'Études d\'impact, plans de gestion environnementale et sociale, audits environnementaux, plans de réinstallation.', famille: 'SERVICES',
    contexte: 'Préciser le projet, sa catégorie, la zone d\'influence et les exigences du bailleur éventuel.',
    contextePoints: ['Description du projet et zone d\'influence', 'Exigences réglementaires et du bailleur (sauvegardes)'],
    objectifs: ['Identifier et évaluer les impacts environnementaux et sociaux du projet [●].', 'Proposer un plan de gestion environnementale et sociale (PGES) chiffré.', 'Obtenir la validation réglementaire de l\'étude avant le démarrage des travaux.'],
    prestations: ['Cadrage et consultation du public : [●] séances', 'État initial (milieu physique, biologique, humain) : [●]', 'Analyse des alternatives et des impacts : [●]', 'Plan de gestion environnementale et sociale avec coûts et responsabilités', 'Plan d\'action de réinstallation si nécessaire : [●]', 'Rapport pour validation réglementaire et audiences publiques', 'Appui à la validation par l\'autorité compétente'],
    livrables: ['Note de cadrage validée', 'Rapport provisoire d\'étude d\'impact', 'PGES et budget associé', 'Rapport final validé et rapport de consultation publique'],
    profil: ['Bureau agréé pour la réalisation d\'études d\'impact', 'Chef de mission environnementaliste confirmé', 'Sociologue / spécialiste des réinstallations', 'Spécialistes biodiversité, eau, bruit selon le projet', 'Références d\'études comparables'],
    references: ['Code de l\'environnement et procédure d\'étude d\'impact (à confirmer auprès de la DEEC)', 'Agrément des bureaux pour les études d\'impact (à confirmer)', 'Politiques de sauvegarde du bailleur le cas échéant'],
    vigilance: ['Consultation publique réelle, avec compte rendu', 'PGES budgétisé et réaliste', 'Indépendance du bureau vis-à-vis du maître d\'ouvrage', 'Délais de validation réglementaire'],
    reception: ['Rapport conforme au plan réglementaire', 'Validation par l\'autorité compétente obtenue', 'Consultation publique tenue et documentée', 'PGES exploitable par l\'entreprise'],
    dureePoints: ['Délai de validation par l\'autorité', 'Saison sèche ou humide pour l\'état initial'],
    questions: ['Quel projet et quelle zone d\'influence ?', 'Quelles exigences réglementaires et du bailleur ?', 'Un déplacement de populations est-il prévu ?', 'Quels risques environnementaux majeurs ?', 'Quel calendrier de validation ?'],
    criteres: [['Méthodologie et compréhension des enjeux', 35], ['Qualification de l\'équipe', 35], ['Références d\'études comparables', 20], ['Plan de travail et consultation', 10]],
    seuil: 75,
  },
  {
    code: 'AUDIT_FINANCES', libelle: 'Audit financier, comptable et organisationnel', description: 'Audits comptables et financiers, audits de performance, de conformité, des marchés publics, organisationnels.', famille: 'SERVICES',
    contexte: 'Préciser l\'entité ou le programme audité, la période et le cadre d\'audit exigé.',
    contextePoints: ['Entité, période et périmètre de l\'audit', 'Référentiel comptable et normes d\'audit applicables'],
    objectifs: ['Exprimer une opinion sur les états financiers de l\'exercice [●].', 'Évaluer le dispositif de contrôle interne et la conformité aux procédures.', 'Formuler des recommandations hiérarchisées avec un plan d\'action.'],
    prestations: ['Planification et prise de connaissance de l\'entité : [●]', 'Revue du contrôle interne et tests de procédures', 'Contrôles substantifs sur les comptes : [●]', 'Revue de conformité (marchés publics, passation, exécution) : [●] marchés', 'Lettre de recommandations (management letter)', 'Restitution à la direction et aux organes de gouvernance', 'Suivi de la mise en œuvre des recommandations précédentes'],
    livrables: ['Plan de mission validé', 'Rapport provisoire contradictoire', 'Rapport d\'audit et opinion', 'Lettre de recommandations et plan d\'action'],
    profil: ['Cabinet inscrit à l\'ordre des experts comptables', 'Associé signataire expérimenté', 'Auditeurs seniors et juniors', 'Références d\'audits d\'entités publiques ou de projets', 'Indépendance attestée'],
    references: ['Normes internationales d\'audit et référentiel comptable applicable (à confirmer)', 'Cadre OHADA et plan comptable applicable (à confirmer)', 'Contrôle de la Cour des comptes et des corps de contrôle'],
    vigilance: ['Indépendance : aucune mission de conseil conflictuelle', 'Accès aux documents et au personnel garanti par l\'autorité', 'Procédure contradictoire avant le rapport final', 'Confidentialité des informations'],
    reception: ['Rapport conforme aux normes d\'audit', 'Opinion argumentée et documentée', 'Recommandations hiérarchisées', 'Restitution tenue'],
    dureePoints: ['Dates de clôture des comptes', 'Délais de la procédure contradictoire'],
    questions: ['Quelle entité, quelle période et quel type d\'audit ?', 'Quel référentiel comptable ?', 'Faut-il aussi une revue de conformité des marchés ?', 'Quelle date de rapport final ?', 'Des audits précédents existent-ils ?'],
    criteres: [['Méthodologie d\'audit et plan de mission', 30], ['Qualification de l\'équipe et de l\'associé', 40], ['Références d\'audits comparables', 20], ['Indépendance et confidentialité', 10]],
    seuil: 75,
  },
  {
    code: 'SUIVI_EVALUATION', libelle: 'Suivi-évaluation de projets et programmes', description: 'Évaluations à mi-parcours et finales, dispositifs de suivi, études d\'impact, collecte de données de suivi.', famille: 'SERVICES',
    contexte: 'Préciser le projet ou programme évalué, sa théorie du changement, son cadre de résultats et ses financeurs.',
    contextePoints: ['Projet évalué, période, budget et zone', 'Cadre de résultats et indicateurs existants'],
    objectifs: ['Évaluer la pertinence, l\'efficacité, l\'efficience, l\'impact et la durabilité du projet [●].', 'Formuler des leçons apprises et des recommandations opérationnelles.', 'Renforcer le dispositif de suivi de l\'institution.'],
    prestations: ['Revue documentaire et reconstitution de la logique d\'intervention : [●]', 'Conception de la méthodologie d\'évaluation et des outils : [●]', 'Collecte de données quantitatives et qualitatives : [●] enquêtés / entretiens', 'Analyse, triangulation et formulation des conclusions', 'Atelier de restitution et de validation', 'Recommandations hiérarchisées et plan d\'action', 'Renforcement du dispositif de suivi'],
    livrables: ['Note méthodologique validée', 'Rapport provisoire', 'Rapport final et synthèse', 'Base de données anonymisée et outils de collecte'],
    profil: ['Chef de mission évaluateur confirmé', 'Experts thématiques', 'Spécialiste des statistiques', 'Enquêteurs formés', 'Références d\'évaluations comparables'],
    references: ['Critères d\'évaluation internationaux (pertinence, efficacité, efficience, impact, durabilité)', 'Code d\'éthique de l\'évaluation', 'Protection des données des enquêtés'],
    vigilance: ['Indépendance de l\'évaluateur vis-à-vis du projet', 'Échantillon représentatif et taille justifiée', 'Protection des enquêtés', 'Recommandations réalistes et priorisées'],
    reception: ['Méthodologie respectée', 'Rapports conformes au plan', 'Données remises', 'Atelier de restitution tenu'],
    dureePoints: ['Période de collecte sur le terrain', 'Délais d\'examen des rapports'],
    questions: ['Quel projet évaluer, sur quelle période ?', 'Évaluation à mi-parcours ou finale ?', 'Quels critères et quelles questions d\'évaluation ?', 'Quelle zone et quel échantillon ?', 'Quel public pour la restitution ?'],
    criteres: [['Méthodologie d\'évaluation', 35], ['Qualification de l\'équipe', 35], ['Références d\'évaluations similaires', 20], ['Plan de collecte et outils', 10]],
    seuil: 75,
  },
  {
    code: 'ENQUETES_STATISTIQUES', libelle: 'Enquêtes, collecte et analyse de données', description: 'Enquêtes ménages et entreprises, recensements, collecte numérique, traitement statistique.', famille: 'SERVICES',
    contexte: 'Préciser l\'objet de l\'enquête, la population cible, la couverture géographique et les indicateurs à produire.',
    contextePoints: ['Population cible et couverture', 'Indicateurs à produire et exploitation attendue'],
    objectifs: ['Produire des indicateurs fiables sur [●] pour [●] ménages / unités.', 'Garantir la qualité des données (taux de réponse, contrôles).', 'Remettre une base de données documentée et exploitable.'],
    prestations: ['Conception du questionnaire et du plan de sondage : [●]', 'Pré-test et ajustement des outils', 'Recrutement et formation des enquêteurs : [●]', 'Collecte numérique sur tablettes avec contrôle à distance', 'Contrôle de qualité et suivi des taux de réponse', 'Apurement, pondération et analyse des données', 'Rapport statistique et base de données documentée'],
    livrables: ['Plan de sondage et questionnaires validés', 'Rapport de pré-test', 'Base de données apurée et dictionnaire des variables', 'Rapport d\'analyse et tableaux'],
    profil: ['Statisticien-méthodologue', 'Responsable du terrain et superviseurs', 'Enquêteurs formés maîtrisant les langues locales', 'Outils de collecte numérique', 'Références d\'enquêtes de grande taille'],
    references: ['Coordination avec l\'agence nationale de la statistique et de la démographie (ANSD) (à confirmer)', 'Loi sur les données personnelles et autorisation de la CDP (à confirmer)', 'Standards internationaux d\'enquête'],
    vigilance: ['Protection des données personnelles et anonymisation', 'Taille d\'échantillon justifiée par le plan de sondage', 'Contrôle des enquêteurs pour éviter les faux questionnaires', 'Calendrier de collecte hors périodes de forte activité'],
    reception: ['Taux de réponse atteint', 'Base de données conforme au dictionnaire', 'Rapport d\'analyse validé', 'Données remises à l\'autorité'],
    dureePoints: ['Période de collecte', 'Délai de traitement des données'],
    questions: ['Quel est l\'objet de l\'enquête et quelle est la population cible ?', 'Quelle couverture géographique et quelle taille d\'échantillon ?', 'Quels indicateurs doivent être produits ?', 'Collecte papier ou numérique ?', 'Quelle autorisation de données personnelles ?'],
    criteres: [['Méthodologie et plan de sondage', 35], ['Qualification de l\'équipe', 30], ['Références d\'enquêtes comparables', 20], ['Organisation du terrain et contrôle qualité', 15]],
    seuil: 75,
  },
  {
    code: 'JURIDIQUE_CONSEIL', libelle: 'Conseil juridique et rédaction de textes', description: 'Assistance juridique, rédaction de textes, contentieux, négociation de contrats, conformité.', famille: 'SERVICES',
    contexte: 'Préciser la question juridique, les textes concernés et la décision que le conseil doit permettre.',
    contextePoints: ['Question juridique et enjeu', 'Textes applicables et jurisprudence connue'],
    objectifs: ['Fournir une analyse juridique documentée sur [●] avant le [●].', 'Rédiger ou réviser [●] textes ou contrats conformes au droit applicable.', 'Sécuriser juridiquement la position de l\'autorité.'],
    prestations: ['Analyse juridique et revue des textes : [●]', 'Consultation écrite ou avis motivé : [●]', 'Rédaction ou révision de contrats, décrets, arrêtés ou conventions : [●]', 'Assistance à la négociation : [●] séances', 'Représentation ou assistance en contentieux le cas échéant', 'Veille juridique ponctuelle', 'Formation juridique des équipes'],
    livrables: ['Note de cadrage juridique', 'Avis juridique motivé', 'Projets de textes ou contrats', 'Synthèse et recommandations'],
    profil: ['Avocat inscrit au barreau ou juriste confirmé', 'Spécialité dans le domaine concerné', 'Connaissance du droit OHADA et du droit public sénégalais', 'Références de missions comparables', 'Absence de conflit d\'intérêts'],
    references: ['Droit OHADA et droit national applicable (à confirmer)', 'Règles de déontologie du barreau', 'Code des marchés publics pour les contrats concernés'],
    vigilance: ['Conflit d\'intérêts avec les parties adverses', 'Honoraires forfaitaires ou au temps passé : préciser', 'Confidentialité de l\'avis', 'Délais d\'avis compatibles avec les échéances'],
    reception: ['Avis motivé et complet', 'Textes remis dans les formats convenus', 'Délais respectés', 'Confidentialité respectée'],
    dureePoints: ['Échéances impératives des avis', 'Durée de la mission'],
    questions: ['Quelle question juridique et quel enjeu ?', 'Quels textes ou contrats sont concernés ?', 'Quelle échéance ?', 'Une représentation en justice est-elle attendue ?', 'Quel mode de rémunération ?'],
    criteres: [['Compréhension de la question et méthode', 30], ['Qualification de l\'équipe', 40], ['Références comparables', 20], ['Organisation et délais', 10]],
    seuil: 75,
  },
  {
    code: 'DEVELOPPEMENT_LOGICIEL', libelle: 'Développement de logiciels et systèmes d\'information', description: 'Conception, développement, hébergement et maintenance d\'applications, ERP, portails, systèmes d\'information.', famille: 'SERVICES',
    contexte: 'Préciser les processus à informatiser, les utilisateurs, l\'existant et l\'environnement technique.',
    contextePoints: ['Processus à informatiser et utilisateurs', 'Systèmes existants et interfaces à prévoir'],
    objectifs: ['Mettre en service un système d\'information couvrant [●] processus pour [●] utilisateurs avant le [●].', 'Garantir la sécurité, la disponibilité et l\'interopérabilité du système.', 'Transférer la maîtrise technique à l\'équipe de l\'institution.'],
    prestations: ['Analyse des besoins et spécifications fonctionnelles : [●]', 'Conception technique et architecture : [●]', 'Développement itératif et tests : [●] versions', 'Interfaces avec les systèmes existants : [●]', 'Migration et reprise des données : [●]', 'Hébergement, sauvegardes et plan de reprise d\'activité', 'Formation, documentation et maintenance corrective et évolutive pendant [●] mois'],
    livrables: ['Spécifications fonctionnelles et techniques validées', 'Versions livrées à chaque itération avec cahier de recette', 'Code source, documentation et manuels', 'Rapport de formation et plan de maintenance'],
    profil: ['Chef de projet certifié', 'Architecte et développeurs seniors', 'Spécialiste de la sécurité applicative', 'Références de systèmes comparables', 'Capacité de support au Sénégal'],
    references: ['Cadre de l\'ADIE pour les systèmes d\'information de l\'État (à confirmer)', 'Loi sur les données personnelles (à confirmer)', 'Standards d\'interopérabilité et de sécurité applicatifs'],
    vigilance: ['Propriété du code source et licences à l\'autorité', 'Réversibilité : pas de dépendance exclusive', 'Tests de recette détaillés avant chaque paiement', 'Hébergement et souveraineté des données'],
    reception: ['Recette fonctionnelle et technique réussie', 'Tests de sécurité et de charge réalisés', 'Code source et documentation remis', 'Formation réalisée'],
    dureePoints: ['Calendrier des itérations', 'Période de garantie et de maintenance'],
    questions: ['Quels processus faut-il informatiser et pour quels utilisateurs ?', 'Quels systèmes existants et quelles interfaces ?', 'Quel hébergement est prévu ?', 'À qui appartient le code source ?', 'Quelle maintenance après mise en service ?'],
    criteres: [['Compréhension et solution technique proposée', 30], ['Qualification de l\'équipe', 30], ['Références de projets comparables', 20], ['Sécurité, maintenance et transfert de compétences', 20]],
    seuil: 75,
  },
  {
    code: 'CYBERSECURITE', libelle: 'Cybersécurité et audit des systèmes d\'information', description: 'Audit de sécurité, tests d\'intrusion, mise en conformité, plans de continuité, sensibilisation.', famille: 'SERVICES',
    contexte: 'Préciser le périmètre des systèmes, les enjeux de sécurité et les audits précédents.',
    contextePoints: ['Périmètre des systèmes et criticité', 'Incidents ou audits passés'],
    objectifs: ['Évaluer le niveau de sécurité de [●] et identifier les vulnérabilités critiques.', 'Établir un plan de remédiation priorisé et chiffré.', 'Sensibiliser le personnel aux risques cyber.'],
    prestations: ['Cadrage et inventaire du périmètre : [●]', 'Audit de configuration et d\'architecture : [●]', 'Tests d\'intrusion internes et externes (avec autorisation écrite) : [●]', 'Revue de la gouvernance et des politiques de sécurité', 'Plan de remédiation priorisé et chiffré', 'Plan de continuité et de reprise d\'activité : [●]', 'Sensibilisation et exercices de crise'],
    livrables: ['Plan de mission et règles d\'engagement signés', 'Rapport d\'audit avec criticité des vulnérabilités', 'Plan de remédiation', 'Rapport de sensibilisation'],
    profil: ['Auditeurs certifiés en sécurité des systèmes d\'information', 'Chef de mission confirmé', 'Outils reconnus d\'audit', 'Références d\'audits comparables', 'Engagement de confidentialité'],
    references: ['Cadre national de cybersécurité et autorités compétentes (à confirmer)', 'Loi sur la cybercriminalité et sur les données personnelles (à confirmer)', 'Référentiels internationaux de sécurité de l\'information'],
    vigilance: ['Règles d\'engagement écrites avant tout test d\'intrusion', 'Confidentialité des vulnérabilités', 'Accès sécurisé aux données de test', 'Remédiation suivie, pas seulement constatée'],
    reception: ['Rapport conforme au plan de mission', 'Vulnérabilités documentées et priorisées', 'Plan de remédiation chiffré', 'Restitution tenue'],
    dureePoints: ['Fenêtres de test convenues', 'Délai de remédiation'],
    questions: ['Quel périmètre de systèmes auditer ?', 'Des tests d\'intrusion sont-ils autorisés ?', 'Quels référentiels de sécurité ?', 'Quelles données sensibles sont concernées ?', 'Quel accompagnement à la remédiation ?'],
    criteres: [['Méthodologie d\'audit', 30], ['Certifications et qualification de l\'équipe', 35], ['Références d\'audits comparables', 20], ['Plan de remédiation et confidentialité', 15]],
    seuil: 75,
  },
  {
    code: 'TOPOGRAPHIE_SIG', libelle: 'Topographie, cartographie et systèmes d\'information géographique', description: 'Levés topographiques, cadastre, cartographie, SIG, télédétection, drones.', famille: 'SERVICES',
    contexte: 'Préciser la zone, l\'échelle, la précision requise et l\'usage des données produites.',
    contextePoints: ['Emprise, échelle et précision', 'Usage prévu (aménagement, cadastre, planification)'],
    objectifs: ['Produire les levés et la cartographie de [●] hectares / [●] km à la précision de [●] cm.', 'Livrer des données SIG géoréférencées documentées.', 'Former les agents de l\'institution à leur exploitation.'],
    prestations: ['Implantation du canevas et rattachement au système géodésique national : [●]', 'Levés topographiques ou par drone : [●] ha', 'Traitement, restitution et production des plans et cartes : [●]', 'Base de données SIG avec métadonnées : [●] couches', 'Contrôles de précision et rapport de qualité', 'Remise des données brutes et traitées', 'Formation à l\'exploitation du SIG'],
    livrables: ['Rapport de canevas et de précision', 'Plans et cartes aux formats convenus', 'Base de données SIG documentée', 'Rapport de formation'],
    profil: ['Géomètre-expert ou ingénieur géomètre', 'Opérateurs topographes et pilotes de drone autorisés', 'Matériel (stations, GNSS, drone) étalonné', 'Références de levés comparables', 'Logiciels de traitement et SIG'],
    references: ['Système géodésique national de référence (à confirmer)', 'Autorisation d\'utilisation de drones auprès de l\'autorité compétente (à confirmer)', 'Réglementation du cadastre et de la publicité foncière'],
    vigilance: ['Étalonnage des instruments attesté', 'Autorisation de vol de drone avant tout levé', 'Livraison des données brutes en plus des produits', 'Formats ouverts et métadonnées'],
    reception: ['Contrôle de précision sur points témoins', 'Plans conformes aux normes de représentation', 'Base SIG complète', 'Formation réalisée'],
    dureePoints: ['Conditions météorologiques', 'Délais de traitement'],
    questions: ['Quelle emprise et quelle échelle ?', 'Quelle précision est exigée ?', 'Quels formats de données ?', 'Un survol par drone est-il envisagé ?', 'Qui exploitera le SIG ?'],
    criteres: [['Méthodologie et matériel', 30], ['Qualification de l\'équipe', 30], ['Références', 20], ['Qualité des données et contrôle', 20]],
    seuil: 75,
  },
  {
    code: 'AMO_GESTION_PROJET', libelle: 'Assistance à maîtrise d\'ouvrage et gestion de projet', description: 'AMO, unités de gestion de projet, pilotage, passation et suivi fiduciaire, appui institutionnel.', famille: 'SERVICES',
    contexte: 'Préciser le projet ou programme, son financement, ses composantes et l\'organisation de la maîtrise d\'ouvrage.',
    contextePoints: ['Composantes, budget et calendrier du programme', 'Organisation de la maîtrise d\'ouvrage et rôle de l\'assistant'],
    objectifs: ['Appuyer l\'autorité dans la planification, la passation et le suivi du projet [●].', 'Respecter les délais, les coûts et les règles fiduciaires.', 'Renforcer durablement les capacités de l\'équipe de l\'institution.'],
    prestations: ['Planification et plan de passation des marchés : [●]', 'Appui à la préparation des dossiers et à la passation : [●] marchés', 'Suivi budgétaire et financier, reporting aux bailleurs : [●]', 'Gestion des risques et suivi du calendrier', 'Suivi des contrats et des paiements', 'Rapports d\'avancement périodiques', 'Transfert de compétences et formation de l\'équipe'],
    livrables: ['Plan de travail et plan de passation', 'Rapports trimestriels d\'avancement', 'Tableaux de bord de suivi', 'Rapport de fin de mission et plan de pérennisation'],
    profil: ['Chef de projet / coordonnateur confirmé', 'Spécialiste en passation de marchés', 'Spécialiste en gestion financière', 'Références d\'AMO sur des programmes comparables', 'Connaissance des règles des bailleurs'],
    references: ['Code des marchés publics et règles du bailleur (à confirmer)', 'Procédures fiduciaires du programme', 'Règles de déontologie et conflits d\'intérêts'],
    vigilance: ['L\'assistant conseille, l\'autorité décide', 'Éviter la substitution durable à l\'équipe de l\'autorité', 'Définir le nombre de jours-experts et leur répartition', 'Conflit d\'intérêts avec les entreprises du programme'],
    reception: ['Rapports périodiques conformes', 'Plan de passation respecté', 'Capacités de l\'équipe renforcées', 'Rapport de fin de mission remis'],
    dureePoints: ['Durée de la mission', 'Calendrier du programme'],
    questions: ['Quel programme et quelle durée de mission ?', 'Quelles fonctions l\'assistant doit-il couvrir ?', 'Quel financeur et quelles règles ?', 'Quelle équipe sera accompagnée ?', 'Comment assurer le transfert de compétences ?'],
    criteres: [['Compréhension et plan de travail', 30], ['Qualification du chef de projet et de l\'équipe', 40], ['Références d\'AMO comparables', 20], ['Transfert de compétences', 10]],
    seuil: 75,
  },
]

// Modèles génériques par famille de marché (aucun corps de métier) : socle commun quand aucun modèle sectoriel ne convient.
const gen = (code, libelle, nature, famille, extra) => ({
  generic: true, code, libelle, description: libelle, nature, famille,
  contexte: 'Présenter le cadre institutionnel, le besoin et sa justification.',
  objectifs: ['Atteindre [●] d\'ici le [●].', 'Respecter les exigences de qualité et de délai définies.', 'Assurer le transfert ou la remise des résultats à l\'autorité.'],
  questions: ['Quel est l\'objet précis du marché ?', 'Où et quand doit-il être exécuté ?', 'Quelles quantités ou quel périmètre ?', 'Quels sont les résultats attendus et comment les mesurer ?', 'Quelles contraintes particulières ?'],
  criteres: [], ...extra,
})
export const GENERIQUES = [
  gen('TRAVAUX', 'Travaux (modèle générique)', 'TRAVAUX', 'TRAVAUX', {
    prestations: ['Installation et organisation du chantier : [●]', 'Travaux principaux selon le descriptif : [●]', 'Travaux annexes et finitions : [●]', 'Repli de chantier et remise en état'],
    livrables: ['Programme d\'exécution et planning', 'Rapports d\'avancement', 'Plans de récolement et dossier des ouvrages exécutés'],
    profil: ['Conducteur de travaux', 'Chef de chantier', 'Matériel principal de chantier', 'Références de travaux similaires'],
    references: ['Normes et règles de l\'art applicables aux ouvrages concernés (à préciser)'],
    vigilance: ['Études techniques disponibles avant l\'appel d\'offres', 'Contrôle des matériaux', 'Hygiène, sécurité et environnement'],
    reception: ['Conformité aux plans et au CCTP', 'Essais conformes', 'Levée des réserves'],
  }),
  gen('FOURNITURES', 'Fournitures (modèle générique)', 'FOURNITURES', 'FOURNITURES', {
    prestations: ['Articles : caractéristiques minimales (ou équivalent), quantités par lot : [●]', 'Conditionnement et transport : [●]', 'Livraison aux lieux désignés : [●]', 'Installation et mise en service si nécessaire'],
    livrables: ['Livraison selon le calendrier', 'Documents de livraison et de garantie', 'Notice d\'utilisation en français'],
    profil: ['Fournisseur ou distributeur établi', 'Service après-vente au Sénégal', 'Références de fournitures comparables'],
    references: ['Normes de qualité applicables ou équivalentes (à préciser)'],
    vigilance: ['Ne jamais imposer une marque sans « ou équivalent »', 'Échantillons si nécessaire', 'Garantie et pièces détachées'],
    reception: ['Conformité aux spécifications', 'Contrôle quantitatif et qualitatif', 'Garantie remise'],
  }),
  gen('SERVICES', 'Services courants (modèle générique)', 'SERVICES_COURANTS', 'SERVICES', {
    prestations: ['Prestations récurrentes : nature, fréquence, étendue : [●]', 'Moyens humains et matériels mobilisés : [●]', 'Encadrement et contrôle qualité', 'Rapports d\'activité périodiques'],
    livrables: ['Plan de mise en œuvre', 'Rapports d\'activité périodiques', 'Rapport final'],
    profil: ['Prestataire établi', 'Personnel qualifié', 'Références de services comparables'],
    references: ['Réglementation applicable à l\'activité (à préciser)'],
    vigilance: ['Respect du droit du travail et des obligations sociales', 'Indicateurs de qualité mesurables', 'Prix anormalement bas'],
    reception: ['Service conforme au plan', 'Rapports validés', 'Indicateurs de qualité atteints'],
  }),
  gen('PRESTATIONS_INTELLECTUELLES', 'Prestations intellectuelles (modèle générique)', 'PRESTATIONS_INTELLECTUELLES', 'SERVICES', {
    prestations: ['Revue documentaire et cadrage : [●]', 'Analyse et production des livrables : [●]', 'Consultation des parties prenantes : [●]', 'Restitution et validation', 'Transfert de compétences'],
    livrables: ['Rapport de démarrage', 'Rapport provisoire', 'Rapport final et synthèse'],
    profil: ['Chef de mission', 'Experts thématiques', 'Références d\'études comparables'],
    references: ['Termes de référence types de la DCMP pour les prestations intellectuelles (à confirmer)'],
    vigilance: ['Indépendance et absence de conflit d\'intérêts', 'Livrables précis', 'Cession des droits à l\'autorité'],
    reception: ['Rapports conformes au plan', 'Observations intégrées', 'Restitution tenue'],
    criteres: [['Compréhension des TDR et méthodologie', 35], ['Qualification et expérience de l\'équipe', 40], ['Références', 15], ['Plan de travail', 10]],
  }),
]
